import {
	Home,
	Info,
	Library,
	Calculator,
	Globe,
	Info as InfoIcon,
	BookOpen,
	Clock,
	Headset,
	Activity,
	Gamepad2,
	HelpCircle,
	CheckSquare,
	FileText,
	StickyNote,
	Target,
	History,
	UserCheck,
	User,
	Phone,
	Settings,
	Cog,
	Grid3X3,
	Table,
	FolderTree,
	UserX,
	X,
	MessageSquare,
	AudioWaveform,
	TrendingUp,
	Columns4,
	ScrollText,
	MessageCircleReply,
} from 'lucide-react'

export const icons = {
	home: <Home className="w-4 h-4" />,
	question: <HelpCircle className="w-4 h-4" />,
	checklist: <CheckSquare className="w-4 h-4" />,
	textSlash: <FileText className="w-4 h-4" />,
	note: <StickyNote className="w-4 h-4" />,
	tipify: <Target className="w-4 h-4" />,
	calc: <Calculator className="w-4 h-4" />,
	web: <Globe className="w-4 h-4" />,
	Headset: <Headset className="w-4 h-4" />,
	Activity: <Activity className="w-4 h-4" />,
	comments: <MessageSquare className="w-4 h-4" />,
	library: <Library className="w-4 h-4" />,
	info: <Info className="w-4 h-4" />,
	catalogue: <BookOpen className="w-4 h-4" />,
	timeLine: <History className="w-4 h-4" />,
	admin: <UserCheck className="w-4 h-4" />,
	user: <User className="w-4 h-4" />,
	phone: <Phone className="w-4 h-4" />,
	gears: <Settings className="w-4 h-4" />,
	gear: <Cog className="w-4 h-4" />,
	matriz: <Grid3X3 className="w-4 h-4" />,
	table: <Table className="w-4 h-4" />,
	filesTree: <FolderTree className="w-4 h-4" />,
	userX: <UserX className="w-4 h-4" />,
	x: <X className="w-4 h-4" />,
	clock: <Clock className="w-4 h-4" />,
	ventas: <TrendingUp className="w-4 h-4" />,
	AudioWaveform: <AudioWaveform className="w-4 h-4" />,
	Gamepad2: <Gamepad2 className="w-4 h-4" />,
	ScrollText: <ScrollText className="w-4 h-4" />,
	MessageCircleReply: <MessageCircleReply className="w-4 h-4" />,
}
